export enum ErrorKey {
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHORIZED_PROJECT = 'UNAUTHORIZED_PROJECT',
  PENDING_PROJECT_INVITE = 'PENDING_PROJECT_INVITE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
